### PR TITLE
Update JVM connectors to v1.0.1

### PR DESCRIPTION
**Pull request by GavinRay97**

### CODE REVIEW

**Comment by codedmart** [comment]
@gneeri is this still a draft?

**Comment by GavinRay97** [comment]
This was in draft pending confirmation from other folks that all was good -- should be alright to merge now based on feedback

**Comment by gneeri** [comment]
> This was in draft pending confirmation from other folks that all was good -- should be alright to merge now based on feedback

Great, I'll go ahead and add a review and merge this now. Thanks.

**Comment by codedmart** [comment]
Closing in favor of #311

**Pull request closed without merging**
