### PR TITLE
RFC: Env var mapping

### PR DESCRIPTION
**Pull request by SandeepSamba**
[Rendered](https://github.com/hasura/ndc-hub/blob/19ee2f4d5e48bea31befbe2a99410caf4b9bf50f/rfcs/0006-env-mapping.md)

### CODE REVIEW

**Comment by nullxone** [comment]
```typescript
// Instead of
type Val = string | ValFromEnv

// Let's do
type Val = { value: string } | ValFromEnv
```

It's easier for tooling to parse and handle this type. And this is ok because the user is not generally editing this file, it is autogenerated.

**Comment by SandeepSamba** [comment]
> ```ts
> // Instead of
> type Val = string | ValFromEnv
> 
> // Let's do
> type Val = { value: string } | ValFromEnv
> ```
> 
> It's easier for tooling to parse and handle this type. And this is ok because the user is not generally editing this file, it is autogenerated.

Done

**Comment by nullxone** [comment]
A solution that does not require changes to the connector spec is to define the connector.yaml as

```yaml
  kind: Connector
  definition:
    name: mypg
    hasura-hub: hasura/postgres:2
    envFile: ./.env.cloud2
    env:
      - CONNECTION_URI=${APP_MYPG_CONNECTION_URI}
```

Then we can still use a single env file, but do the mapping at the CLI level.

native (non docker) connectors still need some mapping, but we can assume that they mostly take user specified env vars (like with typescript), so we can solve that mapping later.

**Comment by SandeepSamba** [comment]
Withdrawing the RFC as we will handle the mapping at the CLI end, similar to Akshaya's proposal.

**Pull request closed without merging**
